"""
Pure In-Memory Enterprise Partition Scheduler for HunterOS Engage.

Responsibilities:
    - Pure execution planning: Zero database queries and zero transport/Celery calls.
    - Group candidate EventRecords by deterministic partition keys.
    - Resolve hierarchical ordering policies and lock timeout overrides.
    - Evaluate active partition locks via AbstractPartitionLockManager.
    - Apply pluggable SchedulingPolicy (Round-Robin / Deficit Round-Robin) to guarantee fairness.
    - Generate an immutable, deterministic PartitionDispatchPlan.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Set
from uuid import UUID

from app.events.store.models import EventRecord
from app.events.partitioning.resolver import PartitionResolver
from app.events.partitioning.ordering import OrderingPolicy, OrderingPolicyResolver
from app.events.partitioning.lock_manager import AbstractPartitionLockManager, get_lock_manager
from app.events.partitioning.config import PartitionConfig, partition_config
from app.events.partitioning.fairness import AbstractSchedulingPolicy, get_scheduling_policy
from app.utils.logger import get_logger

logger = get_logger(__name__)


@dataclass(frozen=True)
class ScheduledDispatch:
    """
    Immutable specification of a single event scheduled for dispatch.
    """
    event_id: UUID
    partition_key: str
    ordering_policy: OrderingPolicy
    occurred_at: datetime
    trace_id: Optional[str] = None
    lock_timeout_seconds: float = 60.0


@dataclass(frozen=True)
class PartitionDispatchPlan:
    """
    Immutable output generated by the EnterprisePartitionScheduler.
    """
    scheduled_dispatches: List[ScheduledDispatch]
    deferred_records: List[EventRecord]
    active_partition_count: int
    waiting_partition_count: int
    largest_partition_name: Optional[str]
    largest_partition_size: int
    average_events_per_partition: float
    oldest_waiting_partition: Optional[str]
    metrics: Dict[str, Any] = field(default_factory=dict)

    @property
    def total_scheduled(self) -> int:
        return len(self.scheduled_dispatches)

    @property
    def total_deferred(self) -> int:
        return len(self.deferred_records)


class EnterprisePartitionScheduler:
    """
    Pure in-memory execution planning engine for event dispatching.
    """

    def __init__(
        self,
        lock_manager: Optional[AbstractPartitionLockManager] = None,
        config: Optional[PartitionConfig] = None,
        scheduling_policy: Optional[AbstractSchedulingPolicy] = None,
    ):
        self.lock_manager = lock_manager or get_lock_manager()
        self.config = config or partition_config
        self.scheduling_policy = scheduling_policy or get_scheduling_policy(self.config.fairness_policy)
        self._scheduler_cycles: int = 0

    def plan_dispatch(
        self,
        records: List[EventRecord],
        batch_size: Optional[int] = None,
    ) -> PartitionDispatchPlan:
        """
        Plans the ordered execution schedule for candidate EventRecords without executing DB or transport calls.

        Args:
            records: Candidate EventRecord instances pre-fetched by Outbox Dispatcher.
            batch_size: Maximum total events to include in this plan (defaults to config).

        Returns:
            PartitionDispatchPlan detailing scheduled dispatches and deferred partitions.
        """
        self._scheduler_cycles += 1
        effective_batch_size = batch_size or self.config.partition_batch_size

        if not records:
            return PartitionDispatchPlan(
                scheduled_dispatches=[],
                deferred_records=[],
                active_partition_count=0,
                waiting_partition_count=0,
                largest_partition_name=None,
                largest_partition_size=0,
                average_events_per_partition=0.0,
                oldest_waiting_partition=None,
                metrics={"scheduler_cycles": self._scheduler_cycles},
            )

        # 1. Group records by partition_key and resolve metadata
        partition_groups: Dict[str, List[EventRecord]] = {}
        partition_policies: Dict[str, OrderingPolicy] = {}
        partition_timeouts: Dict[str, float] = {}

        for record in records:
            p_key = PartitionResolver.resolve_partition_key(record)
            policy = OrderingPolicyResolver.resolve(record)
            timeout = self._resolve_lock_timeout(record)

            if p_key not in partition_groups:
                partition_groups[p_key] = []
                partition_policies[p_key] = policy
                partition_timeouts[p_key] = timeout

            partition_groups[p_key].append(record)

        # Sort events in each partition by occurred_at ASC for strict internal FIFO
        for p_key in partition_groups:
            partition_groups[p_key].sort(key=lambda r: r.occurred_at)

        # 2. Check active lock status for ORDERED partitions
        locked_partitions: Set[str] = set()
        waiting_partitions: Set[str] = set()
        oldest_waiting_time: Optional[datetime] = None
        oldest_waiting_partition: Optional[str] = None

        for p_key, policy in partition_policies.items():
            if policy == OrderingPolicy.ORDERED:
                if self.lock_manager.is_locked(p_key):
                    locked_partitions.add(p_key)
                    waiting_partitions.add(p_key)
                    # Check age of oldest event waiting in this partition
                    earliest_event = partition_groups[p_key][0]
                    if oldest_waiting_time is None or earliest_event.occurred_at < oldest_waiting_time:
                        oldest_waiting_time = earliest_event.occurred_at
                        oldest_waiting_partition = p_key

        # 3. Apply Fair Scheduling Policy across eligible partitions
        scheduled_records = self.scheduling_policy.schedule(
            partitioned_events=partition_groups,
            batch_size=effective_batch_size,
            locked_partitions=locked_partitions,
            max_per_partition=self.config.max_events_per_partition_per_cycle,
        )

        scheduled_ids = {r.event_id for r in scheduled_records}
        deferred_records = [r for r in records if r.event_id not in scheduled_ids]

        # 4. Map scheduled records into ScheduledDispatch DTOs
        scheduled_dispatches: List[ScheduledDispatch] = []
        for record in scheduled_records:
            p_key = PartitionResolver.resolve_partition_key(record)
            policy = partition_policies[p_key]
            timeout = partition_timeouts[p_key]
            trace_id = getattr(record, "trace_id", None) or str(record.event_id)

            scheduled_dispatches.append(
                ScheduledDispatch(
                    event_id=record.event_id,
                    partition_key=p_key,
                    ordering_policy=policy,
                    occurred_at=record.occurred_at,
                    trace_id=trace_id,
                    lock_timeout_seconds=timeout,
                )
            )

        # 5. Compute partition statistics for observability
        total_partitions = len(partition_groups)
        active_partitions = len([k for k in partition_groups if k not in locked_partitions])
        largest_name = None
        largest_size = 0

        for k, v in partition_groups.items():
            if len(v) > largest_size:
                largest_size = len(v)
                largest_name = k

        avg_events = len(records) / total_partitions if total_partitions > 0 else 0.0

        plan_metrics = {
            "scheduler_cycles": self._scheduler_cycles,
            "total_candidates": len(records),
            "total_scheduled": len(scheduled_dispatches),
            "total_deferred": len(deferred_records),
            "total_partitions": total_partitions,
            "active_partitions": active_partitions,
            "waiting_partitions": len(waiting_partitions),
            "largest_partition_size": largest_size,
            "average_events_per_partition": round(avg_events, 2),
        }

        logger.debug(
            "partition_scheduler_plan_created",
            scheduled=len(scheduled_dispatches),
            deferred=len(deferred_records),
            active_partitions=active_partitions,
            waiting_partitions=len(waiting_partitions),
        )

        return PartitionDispatchPlan(
            scheduled_dispatches=scheduled_dispatches,
            deferred_records=deferred_records,
            active_partition_count=active_partitions,
            waiting_partition_count=len(waiting_partitions),
            largest_partition_name=largest_name,
            largest_partition_size=largest_size,
            average_events_per_partition=round(avg_events, 2),
            oldest_waiting_partition=oldest_waiting_partition,
            metrics=plan_metrics,
        )

    def _resolve_lock_timeout(self, record: EventRecord) -> float:
        """
        Resolves lock timeout using hierarchical override:
            1. Event metadata["lock_timeout_seconds"]
            2. Event attribute lock_timeout_seconds
            3. Global config default
        """
        meta = getattr(record, "metadata_payload", None) or getattr(record, "metadata", None)
        if isinstance(meta, dict) and "lock_timeout_seconds" in meta:
            try:
                return float(meta["lock_timeout_seconds"])
            except (ValueError, TypeError):
                pass

        if hasattr(record, "lock_timeout_seconds"):
            try:
                val = getattr(record, "lock_timeout_seconds")
                if val is not None:
                    return float(val)
            except (ValueError, TypeError):
                pass

        return self.config.lock_timeout_seconds
