image:
  repository: hunteros-engage
  pullPolicy: IfNotPresent
  tag: "latest"

api:
  replicaCount: 2

worker:
  replicaCount: 2

scheduler:
  replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: hunteros.local
      paths:
        - path: /
          pathType: ImplementationSpecific

config:
  ENVIRONMENT: production
  DEBUG: "False"

externalSecrets:
  enabled: true

backup:
  schedule: "0 2 * * *"
  s3Bucket: "hunteros-backups-prod"
