"""
HunterOS Engage — Memory Domain Package (Memory Operations & Lifecycle Management)
"""

from app.domain.memory.audit.service import MemoryAuditService, get_memory_audit_service
from app.domain.memory.commands.bus import MemoryCommandBus, get_memory_command_bus
from app.domain.memory.commands.change_status import ChangeStatusHandler
from app.domain.memory.commands.create_memory import CreateMemoryHandler
from app.domain.memory.commands.delete_memory import DeleteMemoryHandler
from app.domain.memory.commands.models import (
    ArchiveMemoryCommand,
    BaseMemoryCommand,
    ChangeStatusCommand,
    CreateMemoryCommand,
    DeleteMemoryCommand,
    LockMemoryCommand,
    ReplaceMemoryCommand,
    RestoreMemoryCommand,
    UnlockMemoryCommand,
    UpdateMemoryCommand,
)
from app.domain.memory.commands.replace_memory import ReplaceMemoryHandler
from app.domain.memory.commands.restore_memory import RestoreMemoryHandler
from app.domain.memory.commands.update_memory import UpdateMemoryHandler
from app.domain.memory.events.models import (
    BaseMemoryDomainEvent,
    MemoryArchivedDomainEvent,
    MemoryCreatedDomainEvent,
    MemoryDeletedDomainEvent,
    MemoryLockedDomainEvent,
    MemoryRestoredDomainEvent,
    MemoryStatusChangedDomainEvent,
    MemoryUnlockedDomainEvent,
    MemoryUpdatedDomainEvent,
)
from app.domain.memory.events.publisher import (
    AbstractMemoryEventPublisher,
    InMemoryMemoryEventPublisher,
    MemoryEventPublisher,
    get_memory_event_publisher,
)
from app.domain.memory.cache import (
    AbstractMemoryQueryCacheProvider,
    DefaultMemoryQueryCacheProvider,
    get_memory_query_cache,
)
from app.domain.memory.interfaces.read_repository import AbstractMemoryReadRepository
from app.domain.memory.interfaces.service import AbstractMemoryService
from app.domain.memory.interfaces.write_repository import AbstractMemoryWriteRepository
from app.domain.memory.queries import (
    CustomerMemoryDTO,
    ExecutiveViewDTO,
    ExportPreviewQuery,
    GetCursorPaginatedMemoryQuery,
    GetCustomerMemoryQuery,
    GetProjectionQuery,
    GetStatisticsQuery,
    LightweightViewDTO,
    MemoryExportDTO,
    MemoryProjectionEngine,
    MemoryQueryBus,
    MemoryQueryFacade,
    MemorySearchEngine,
    MemoryStatisticsDTO,
    MemoryStatisticsEngine,
    ProjectedMemoryDTO,
    ProjectionRegistry,
    QueryMetricsTracker,
    SearchCompiler,
    SearchCustomerMemoryQuery,
    SummaryViewDTO,
)
from app.domain.memory.models import (
    ChangeType,
    CustomerMemory,
    CustomerMemoryTimelineEvent,
    CustomerMemoryVersion,
    InvalidLifecycleTransitionError,
    LifecycleStatus,
    MemoryChangeLog,
    MemoryConcurrencyConflictError,
    MemoryDomainError,
    MemoryEventType,
    MemoryIdempotencyRecord,
    MemoryImportance,
    MemoryLockedError,
    MemoryTimelineCategory,
)
from app.domain.memory.repositories.read_repository import SqlAlchemyMemoryReadRepository
from app.domain.memory.repositories.write_repository import SqlAlchemyMemoryWriteRepository
from app.domain.memory.repository import MemoryRepository
from app.domain.memory.router import router as memory_router
from app.domain.memory.schemas import (
    BehavioralAttributesBlock,
    CommunicationPreferencesBlock,
    CustomerMemoryBulkCreateRequest,
    CustomerMemoryBulkGetRequest,
    CustomerMemoryBulkUpdateRequest,
    CustomerMemoryCreateRequest,
    CustomerMemoryHistoryResponse,
    CustomerMemoryReplaceRequest,
    CustomerMemoryResponse,
    CustomerMemorySearchResponse,
    CustomerMemorySearchResultItem,
    CustomerMemoryStatusChangeRequest,
    CustomerMemoryTimelineEventResponse,
    CustomerMemoryUpdateRequest,
    CustomerMemoryVersionDetailResponse,
    CustomerMemoryVersionResponse,
    FinancialInfoBlock,
    IdentityBlock,
    JourneySnapshotBlock,
    LocationInfo,
    MemoryChangeLogListResponse,
    MemoryChangeLogResponse,
    MemoryMetadataBlock,
    MemoryPayloadSchema,
    MemorySearchRequest,
    MemoryTimelineFilterRequest,
    MemoryTimelineListResponse,
    PersonalInfoBlock,
    PropertyInfoBlock,
    RelationshipInfoBlock,
)
from app.domain.memory.service import MemoryService
from app.domain.memory.transactions.idempotency import IdempotencyManager, get_idempotency_manager
from app.domain.memory.transactions.unit_of_work import MemoryUnitOfWork
from app.domain.memory.validators.base import (
    AbstractMemoryValidator,
    MemoryValidationError,
    ValidationContext,
    ValidationResult,
)
from app.domain.memory.validators.pipeline import MemoryValidationPipeline, get_validation_pipeline

from app.domain.memory.intelligence import (
    AbstractContextCache,
    ComposedContext,
    CompositionStrategyRegistry,
    ContextBlock,
    ContextBlockType,
    ContextCompletenessReport,
    ContextCompletenessResponse,
    ContextCompletenessStatus,
    ContextCompositionStrategy,
    ContextDescriptor,
    ContextExportEngine,
    ContextLineage,
    ContextLineageResponse,
    ContextMetadata,
    ContextMetadataResponse,
    ContextPipeline,
    ContextRequestOptions,
    ContextSchemaRegistry,
    ContextScope,
    ContextValidationError,
    ContextValidator,
    CrossWorkspaceContextError,
    CustomContextRequest,
    CustomContextResponse,
    Customer360CompositionStrategy,
    CustomerContextResponse,
    DashboardContextExportDTO,
    ExecutiveCompositionStrategy,
    ExecutiveContextExportDTO,
    ExecutiveContextResponse,
    ExportTargetFormat,
    InMemoryContextCache,
    MemoryContextGateway,
    MissingRequiredContextError,
    NoOpContextCache,
    OpportunityCompositionStrategy,
    OpportunityContextResponse,
    OrganizationCompositionStrategy,
    OrganizationContextResponse,
    PropertyCompositionStrategy,
    PropertyContextResponse,
    SelectiveCompositionStrategy,
    StructuredContextDTO,
    context_router,
    default_context_export_engine,
    default_context_schema_registry,
    default_context_validator,
    default_strategy_registry,
    get_memory_context_gateway,
    set_memory_context_gateway,
)

__all__ = [
    # Models & State
    "CustomerMemory",
    "CustomerMemoryVersion",
    "CustomerMemoryTimelineEvent",
    "MemoryChangeLog",
    "MemoryIdempotencyRecord",
    "LifecycleStatus",
    "MemoryTimelineCategory",
    "MemoryImportance",
    "ChangeType",
    "MemoryDomainError",
    "MemoryConcurrencyConflictError",
    "MemoryLockedError",
    "InvalidLifecycleTransitionError",
    # Commands
    "BaseMemoryCommand",
    "CreateMemoryCommand",
    "UpdateMemoryCommand",
    "ReplaceMemoryCommand",
    "DeleteMemoryCommand",
    "RestoreMemoryCommand",
    "ChangeStatusCommand",
    "LockMemoryCommand",
    "UnlockMemoryCommand",
    "ArchiveMemoryCommand",
    "CreateMemoryHandler",
    "UpdateMemoryHandler",
    "ReplaceMemoryHandler",
    "DeleteMemoryHandler",
    "RestoreMemoryHandler",
    "ChangeStatusHandler",
    "MemoryCommandBus",
    "get_memory_command_bus",
    # Events
    "BaseMemoryDomainEvent",
    "MemoryCreatedDomainEvent",
    "MemoryUpdatedDomainEvent",
    "MemoryDeletedDomainEvent",
    "MemoryRestoredDomainEvent",
    "MemoryStatusChangedDomainEvent",
    "MemoryLockedDomainEvent",
    "MemoryUnlockedDomainEvent",
    "MemoryArchivedDomainEvent",
    "AbstractMemoryEventPublisher",
    "InMemoryMemoryEventPublisher",
    "MemoryEventPublisher",
    "get_memory_event_publisher",
    # Validation
    "AbstractMemoryValidator",
    "ValidationContext",
    "ValidationResult",
    "MemoryValidationError",
    "MemoryValidationPipeline",
    "get_validation_pipeline",
    # Audit & Transactions
    "MemoryAuditService",
    "get_memory_audit_service",
    "MemoryUnitOfWork",
    "IdempotencyManager",
    "get_idempotency_manager",
    # Repositories & CQRS
    "AbstractMemoryReadRepository",
    "AbstractMemoryWriteRepository",
    "SqlAlchemyMemoryReadRepository",
    "SqlAlchemyMemoryWriteRepository",
    "MemoryRepository",
    # Service & Router
    "AbstractMemoryService",
    "MemoryService",
    "memory_router",
    # Schemas
    "LocationInfo",
    "IdentityBlock",
    "PersonalInfoBlock",
    "FinancialInfoBlock",
    "PropertyInfoBlock",
    "RelationshipInfoBlock",
    "CommunicationPreferencesBlock",
    "BehavioralAttributesBlock",
    "JourneySnapshotBlock",
    "MemoryMetadataBlock",
    "MemoryPayloadSchema",
    "CustomerMemoryCreateRequest",
    "CustomerMemoryUpdateRequest",
    "CustomerMemoryReplaceRequest",
    "CustomerMemoryStatusChangeRequest",
    "CustomerMemoryBulkCreateRequest",
    "CustomerMemoryBulkGetRequest",
    "CustomerMemoryBulkUpdateRequest",
    "CustomerMemoryResponse",
    "CustomerMemoryVersionResponse",
    "CustomerMemoryVersionDetailResponse",
    "CustomerMemoryTimelineEventResponse",
    "MemoryTimelineFilterRequest",
    "MemoryTimelineListResponse",
    "MemoryChangeLogResponse",
    "MemoryChangeLogListResponse",
    "CustomerMemoryHistoryResponse",
    "MemorySearchRequest",
    "CustomerMemorySearchResponse",
    "CustomerMemorySearchResultItem",
    # Query Intelligence (Phase 2.1.3)
    "AbstractMemoryQueryCacheProvider",
    "DefaultMemoryQueryCacheProvider",
    "get_memory_query_cache",
    "CustomerMemoryDTO",
    "ProjectedMemoryDTO",
    "SummaryViewDTO",
    "ExecutiveViewDTO",
    "LightweightViewDTO",
    "MemoryStatisticsDTO",
    "MemoryExportDTO",
    "MemoryQueryBus",
    "MemoryQueryFacade",
    "MemorySearchEngine",
    "MemoryProjectionEngine",
    "MemoryStatisticsEngine",
    "MemoryExportEngine",
    "SearchCompiler",
    "ProjectionRegistry",
    "QueryMetricsTracker",
    "GetCustomerMemoryQuery",
    "SearchCustomerMemoryQuery",
    "GetCursorPaginatedMemoryQuery",
    "GetProjectionQuery",
    "GetStatisticsQuery",
    "ExportPreviewQuery",
    # Context Integration & Gateway (Phase 2.1.5)
    "MemoryContextGateway",
    "get_memory_context_gateway",
    "set_memory_context_gateway",
    "context_router",
    "ContextPipeline",
    "ContextExportEngine",
    "default_context_export_engine",
    "ComposedContext",
    "ContextBlock",
    "ContextBlockType",
    "ContextCompletenessReport",
    "ContextCompletenessStatus",
    "ContextLineage",
    "ContextMetadata",
    "ContextScope",
    "ExportTargetFormat",
    "ContextDescriptor",
    "ContextSchemaRegistry",
    "default_context_schema_registry",
    "ContextCompositionStrategy",
    "Customer360CompositionStrategy",
    "OrganizationCompositionStrategy",
    "OpportunityCompositionStrategy",
    "PropertyCompositionStrategy",
    "ExecutiveCompositionStrategy",
    "SelectiveCompositionStrategy",
    "CompositionStrategyRegistry",
    "default_strategy_registry",
    "AbstractContextCache",
    "InMemoryContextCache",
    "NoOpContextCache",
    "ContextValidator",
    "default_context_validator",
    "ContextValidationError",
    "CrossWorkspaceContextError",
    "MissingRequiredContextError",
    "ContextMetadataResponse",
    "ContextLineageResponse",
    "ContextCompletenessResponse",
    "ContextRequestOptions",
    "CustomContextRequest",
    "CustomerContextResponse",
    "OrganizationContextResponse",
    "OpportunityContextResponse",
    "PropertyContextResponse",
    "ExecutiveContextResponse",
    "CustomContextResponse",
    "ExecutiveContextExportDTO",
    "DashboardContextExportDTO",
    "StructuredContextDTO",
]


