from app.events.bus.event_bus import EventConsumer, HunterEvent
from app.domain.collaboration.engines.pipeline import DecisionRouter
from app.domain.collaboration.repository import CollaborationRepository
from app.integrations.postgres.database import SessionLocal

class CollaborationEventConsumer(EventConsumer):
    """
    Listens for business events and passes them to the Human-AI Collaboration Layer 
    to extract actionable intents and route work.
    """
    
    @property
    def name(self) -> str:
        return "collaboration_router"

    @property
    def priority(self) -> int:
        return 10 # High priority to route tasks quickly

    async def process(self, event: HunterEvent) -> None:
        # Ignore operational state-change events internally generated by collaboration
        if event.type.startswith("collaboration."):
            return
            
        async with SessionLocal() as session:
            repo = CollaborationRepository(session)
            router = DecisionRouter(repo)
            
            # The intent engine filters out raw events automatically.
            await router.route_event(
                workspace_id=event.workspace_id,
                event_type=event.type,
                payload=event.payload
            )
