from app.events.bus.interfaces import EventConsumer
from app.events.model.base_event import UniversalBaseEvent
from typing import List
from app.domain.collaboration.engines.pipeline import DecisionRouter
from app.domain.collaboration.repository import CollaborationRepository
from app.integrations.postgres.database import get_session

class CollaborationEventConsumer(EventConsumer):
    """
    Listens for business events and passes them to the Human-AI Collaboration Layer 
    to extract actionable intents and route work.
    """
    
    @property
    def name(self) -> str:
        return "collaboration_router"

    def get_subscriptions(self) -> List[type[UniversalBaseEvent]]:
        return [UniversalBaseEvent]

    def get_priority(self) -> int:
        return 10 # High priority to route tasks quickly

    async def handle_event(self, event: UniversalBaseEvent) -> None:
        # Ignore operational state-change events internally generated by collaboration
        if getattr(event, 'event_name', '').startswith("collaboration."):
            return
            
        async with get_session() as session:
            repo = CollaborationRepository(session)
            router = DecisionRouter(repo)
            
            # The intent engine filters out raw events automatically.
            await router.route_event(
                workspace_id=event.workspace_id,
                event_type=event.type,
                payload=event.payload
            )
