"""
HunterOS Engage — Production Configuration Auditor
app/events/certification/audit.py

Automatically audits runtime settings against strict enterprise production standards:
- debug disabled
- tracing sampling configured
- worker concurrency within bounds
- retry backoff and max retry settings
- queue watermarks configured
- lock timeouts and heartbeats tuned
- batch sizes and database connection pools sized
- TLS requirements verified
"""

import os
from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional

from app.core.config import settings
from app.events.certification.config import ProductionCertificationConfig, certification_config


@dataclass
class AuditCheckItem:
    """Individual configuration audit item result."""
    rule_name: str
    category: str
    configured_value: Any
    expected_requirement: str
    passed: bool
    details: str = ""


@dataclass
class ConfigurationAuditReport:
    """Complete report generated by ProductionConfigAuditor."""
    passed: bool
    total_checks: int
    passed_checks: int
    failed_checks: int
    checks: List[AuditCheckItem] = field(default_factory=list)
    remediation_recommendations: List[str] = field(default_factory=list)


class ProductionConfigAuditor:
    """
    Validates application and event configuration against enterprise production requirements.
    """

    def __init__(self, config: Optional[ProductionCertificationConfig] = None):
        self._cfg = config or certification_config

    def audit(self, environment_override: Optional[Dict[str, Any]] = None) -> ConfigurationAuditReport:
        """
        Perform complete audit of active settings.
        """
        env = environment_override or {}
        checks: List[AuditCheckItem] = []
        remediations: List[str] = []

        # 1. Debug Mode Disabled
        # Check settings.DEBUG or env var
        debug_val = env.get("DEBUG", getattr(settings, "DEBUG", False))
        # Handle string "false", "0", etc.
        if isinstance(debug_val, str):
            debug_val = debug_val.lower() in ("true", "1", "yes")
        is_debug_disabled = not bool(debug_val)
        checks.append(AuditCheckItem(
            rule_name="debug_disabled",
            category="Security",
            configured_value=debug_val,
            expected_requirement="DEBUG must be False in production",
            passed=is_debug_disabled,
            details="Debug mode is disabled." if is_debug_disabled else "CRITICAL: Debug mode is enabled! Disable before deploying.",
        ))
        if not is_debug_disabled:
            remediations.append("Set DEBUG=False / ENVIRONMENT=production in deployment environment variables.")

        # 2. Tracing Sampling Configured
        # From tracing manager / env
        trace_sample_rate = env.get("TRACING_SAMPLE_RATE", 1.0)
        has_valid_sampling = 0.0 < float(trace_sample_rate) <= 1.0
        checks.append(AuditCheckItem(
            rule_name="tracing_sampling",
            category="Observability",
            configured_value=trace_sample_rate,
            expected_requirement="0.0 < TRACING_SAMPLE_RATE <= 1.0",
            passed=has_valid_sampling,
            details=f"Trace sampling configured at {trace_sample_rate}.",
        ))

        # 3. Worker Concurrency Settings
        worker_concurrency = int(env.get("WORKER_CONCURRENCY", 8))
        passed_worker = self._cfg.min_worker_concurrency <= worker_concurrency <= self._cfg.max_worker_concurrency
        checks.append(AuditCheckItem(
            rule_name="worker_concurrency",
            category="Execution",
            configured_value=worker_concurrency,
            expected_requirement=f"{self._cfg.min_worker_concurrency} <= WORKER_CONCURRENCY <= {self._cfg.max_worker_concurrency}",
            passed=passed_worker,
            details=f"Worker concurrency set to {worker_concurrency}.",
        ))
        if not passed_worker:
            remediations.append(f"Tune WORKER_CONCURRENCY to within [{self._cfg.min_worker_concurrency}, {self._cfg.max_worker_concurrency}].")

        # 4. Retry Backoff & Max Retries
        max_retries = int(env.get("MAX_RETRIES", 5))
        passed_retries = 1 <= max_retries <= 10
        checks.append(AuditCheckItem(
            rule_name="retry_settings",
            category="Reliability",
            configured_value=max_retries,
            expected_requirement="1 <= MAX_RETRIES <= 10 with exponential backoff",
            passed=passed_retries,
            details=f"Max retries set to {max_retries}.",
        ))

        # 5. Queue Watermarks
        high_watermark = int(env.get("QUEUE_HIGH_WATERMARK", 5000))
        passed_queue = high_watermark >= 1000
        checks.append(AuditCheckItem(
            rule_name="queue_sizes",
            category="FlowControl",
            configured_value=high_watermark,
            expected_requirement="QUEUE_HIGH_WATERMARK >= 1000",
            passed=passed_queue,
            details=f"Queue high watermark set to {high_watermark}.",
        ))

        # 6. Lock Timeout
        lock_timeout = int(env.get("LOCK_TIMEOUT_SECONDS", 30))
        passed_lock = 5 <= lock_timeout <= self._cfg.max_lock_timeout_seconds
        checks.append(AuditCheckItem(
            rule_name="lock_timeout",
            category="Partitioning",
            configured_value=lock_timeout,
            expected_requirement=f"5 <= LOCK_TIMEOUT_SECONDS <= {self._cfg.max_lock_timeout_seconds}",
            passed=passed_lock,
            details=f"Lock timeout set to {lock_timeout}s.",
        ))

        # 7. Cluster Heartbeat
        heartbeat_interval = int(env.get("HEARTBEAT_INTERVAL_SECONDS", 5))
        passed_hb = self._cfg.min_heartbeat_interval_seconds <= heartbeat_interval <= self._cfg.max_heartbeat_interval_seconds
        checks.append(AuditCheckItem(
            rule_name="heartbeat_interval",
            category="Clustering",
            configured_value=heartbeat_interval,
            expected_requirement=f"{self._cfg.min_heartbeat_interval_seconds} <= HEARTBEAT <= {self._cfg.max_heartbeat_interval_seconds}",
            passed=passed_hb,
            details=f"Cluster heartbeat set to {heartbeat_interval}s.",
        ))

        # 8. Outbox Batch Size
        batch_size = int(env.get("OUTBOX_BATCH_SIZE", 100))
        passed_batch = 10 <= batch_size <= 1000
        checks.append(AuditCheckItem(
            rule_name="batch_size",
            category="Throughput",
            configured_value=batch_size,
            expected_requirement="10 <= OUTBOX_BATCH_SIZE <= 1000",
            passed=passed_batch,
            details=f"Outbox polling batch size set to {batch_size}.",
        ))

        # 9. Database Connection Pool Sizing
        db_pool_size = int(env.get("DB_POOL_SIZE", 20))
        passed_db = self._cfg.min_db_pool_size <= db_pool_size <= self._cfg.max_db_pool_size
        checks.append(AuditCheckItem(
            rule_name="connection_pools",
            category="Persistence",
            configured_value=db_pool_size,
            expected_requirement=f"{self._cfg.min_db_pool_size} <= DB_POOL_SIZE <= {self._cfg.max_db_pool_size}",
            passed=passed_db,
            details=f"DB connection pool size set to {db_pool_size}.",
        ))

        # 10. TLS / Encryption in Transit
        db_ssl = str(env.get("DB_SSL_MODE", "prefer")).lower()
        passed_tls = db_ssl in ("require", "verify-ca", "verify-full", "prefer")
        checks.append(AuditCheckItem(
            rule_name="tls_requirements",
            category="Security",
            configured_value=db_ssl,
            expected_requirement="SSL/TLS enabled for external DB and message brokers",
            passed=passed_tls,
            details=f"Database SSL mode configured as '{db_ssl}'.",
        ))

        passed_count = sum(1 for c in checks if c.passed)
        failed_count = len(checks) - passed_count
        overall_passed = failed_count == 0

        return ConfigurationAuditReport(
            passed=overall_passed,
            total_checks=len(checks),
            passed_checks=passed_count,
            failed_checks=failed_count,
            checks=checks,
            remediation_recommendations=remediations,
        )


# Global auditor instance
config_auditor = ProductionConfigAuditor()
