from typing import Any, Dict
import re

def validate_explanation(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Stage 6: Verifies no predictive language, no LLM usage, no AI generation.
    """
    forbidden_terms = ["predict", "might", "could", "AI", "generated by", "language model"]
    reason = data.get('composed_reason', "").lower()
    
    for term in forbidden_terms:
        if term.lower() in reason:
            raise ValueError(f"Validation failed: Forbidden predictive/AI language detected: '{term}'")
            
    return data
